### ISSUE TITLE
Signing screen for Asset Hub -> Relay Chain shows incorrect info

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#1431]
**Describe the bug**
When performing an XCM teleport from Polkadot Asset Hub to Polkadot Relay Chain, the signing popup incorrectly displays that the transaction is from AH -> AH.

For example:
<img width="380" alt="Screenshot 2024-05-09 at 1 48 20 PM" src="https://github.com/TalismanSociety/talisman/assets/3326734/0f66b2ac-bd97-44ab-a5b4-b5b7091584d1">

Extrinsic parameters:
```
dest:
  V3:
    parents: '1'
    interior: Here
beneficiary:
  V3:
    parents: '0'
    interior:
      X1:
        AccountId32:
          network: null
          id: '0x<redacted>'
assets:
  V3:
    - id:
        Concrete:
          parents: '1'
          interior: Here
      fun:
        Fungible: 178,000,000,000
fee_asset_item: '0'
weight_limit: Unlimited
```

**To Reproduce**
Use https://kheopswap.xyz/#/teleport to do a teleport from AH to Polkadot.
